APPLY_FIXES: all
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE: commit
DISABLE:
  - SPELL
  - PYTHON_BLACK
  - PYTHON_PYLINT
  - PYTHON_FLAKE8
  - JAVASCRIPT_PRETTIER
  - PYTHON_MYPY
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
SARIF_REPORTER: true
PYTHON_DEFAULT_STYLE: ruff
VALIDATE_ALL_CODEBASE: true
