pull_request_rules:
  - name: Automatically queue pre-commit Updates
    conditions:
      - files ~= .pre-commit-config.yaml
      - author = renovate[bot]
    actions:
      queue:
      label:
        add:
          - pre-commit
  - name: Automatically queue Dockerfile Updates
    conditions:
      - files ~= Dockerfile
      - author = renovate[bot]
      - check-success = Test Image / API Test
    actions:
      queue:
  - name: Automatically label Dockerfile Updates
    conditions:
      - files ~= Dockerfile
      - author = renovate[bot]
    actions:
      label:
        add:
          - docker
  - name: Automatically queue Github Actions Updates
    conditions:
      - files ~= ^.github/workflows
      - author = renovate[bot]
    actions:
      queue:
      label:
        add:
          - github-actions
  - name: Automatically queue valid Python Dependency Updates
    conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
      - author = renovate[bot]
      - and:
          - check-success = Check Dependency Compatibility
          - check-success = Test Image / API Test
    actions:
      queue:
  - name: Automatically label Python Dependency Updates
    conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
      - author = renovate[bot]
    actions:
      label:
        add:
          - uv
          - python
          - dependencies
  - name: Automatically queue Docker Compose Updates
    conditions:
      - files ~= ^(docker-compose-dev.yaml|docker-compose.yaml)$
      - author = renovate[bot]
    actions:
      queue:
      label:
        add:
          - docker-compose
  - name: Merge pull request when the configuration of Mergify is valid
    conditions:
      - author = MH0386
      - 'title = ci(Mergify): configuration update'
      - head = mergify/MH0386/config-update
    actions:
      merge:
  - name: Comment when a pull request is merged
    conditions:
      - merged
    actions:
      delete_head_branch:
      comment:
        message: >-
          Thank you for your contribution @{{author}}! Your pull request has been
          merged.
  - name: Comment if there is a conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hi @{{author}}, Your PR is in conflict and cannot be merged.
      label:
        add:
          - conflict
  - name: Automatic update of the pull requests
    conditions:
      - -merged
    actions:
      update:
  - name: Add a queue label when PR is queued
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Notify when a PR is removed from the queue
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >-
          Hey @{{author}}, your pull request has been dequeued due to the following
          reason: {{queue_dequeue_reason}}.
          Sorry about that, but you can requeue the PR by using `@mergifyio requeue`
          if you think this was a mistake.
queue_rules:
  - name: default
    update_method: merge
    allow_queue_branch_edit: true
    queue_branch_merge_method: fast-forward
    queue_conditions:
      - and:
          - 'check-success = DeepSource: Secrets'
          - 'check-success = DeepSource: Python'
          - 'check-success = DeepSource: pyproject.toml'
          - 'check-success = DeepSource: Docker'
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = SonarCloud
          - check-success = CodeQL
  - name: dep-update
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = renovate[bot]
