# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
LLM_ADVISOR_ENABLED: true
LLM_PROVIDER: google
LLM_MODEL_NAME: gemini-2.5-flash
LLM_MAX_TOKENS: 1000
LLM_TEMPERATURE: 0.1
VALIDATE_ALL_CODEBASE: true
APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CLOUDFORMATION
  - CSS
  - EDITORCONFIG
  - JAVASCRIPT
  - TEKTON
  - C
  - CPP
  - CSHARP
  - DART
  - EDITORCONFIG
  - GO
  - GROOVY
  - HTML
  - JAVA
  - JSX
  - KOTLIN
  - KUBERNETES
  - LATEX
  - LUA
  - MAKEFILE
  - PERL
  - PHP
  - POWERSHELL
  - PROTOBUF
  - PUPPET
  - R
  - ROBOTFRAMEWORK
  - RST
  - RUBY
  - RUST
  - SALESFORCE
  - SCALA
  - SPELL
  - SQL
  - SWIFT
  - TEKTON
  - TERRAFORM
  - TSX
  - TYPESCRIPT
  - VBDOTNET
  - XML
DISABLE_LINTERS:
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_MYPY
DISABLE_ERRORS_LINTERS:
  - PYTHON_BANDIT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - SPELL_LYCHEE
  - YAML_YAMLLINT
DOCKERFILE_DCLINT_ARGUMENTS: "--fix"
EXCLUDED_DIRECTORIES:
  - ".venv"
PRINT_ALL_FILES: true
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
# JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
# YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
# YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
# YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
# BASH_FILTER_REGEX_EXCLUDE: "(lib)"
# MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
PYTHON_DEFAULT_STYLE: ruff
PYTHON_RUFF_FORMAT_CONFIG_FILE: .github/ruff.toml
GITHUB_STATUS_REPORTER: true
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".venv"
REPOSITORY_TRUFFLEHOG_ARGUMENTS:
  - --exclude-paths=.trufflehogignore
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: true
EMAIL_REPORTER: true
FILEIO_REPORTER: true
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: true
PLUGINS:
  - https://raw.githubusercontent.com/wesley-dean/mega-linter-plugin-dclint/refs/heads/main/mega-linter-plugin-dclint/dclint.megalinter-descriptor.yml
PRE_COMMANDS:
  - command: echo "This is MegaLinter PRE_COMMAND on own MegaLinter ! :)"
    cwd: "root"
POST_COMMANDS:
  - command: echo "This is MegaLinter POST_COMMAND on own MegaLinter ! :)"
    cwd: "workspace"
