LLM_ADVISOR_ENABLED: true
LLM_PROVIDER: google
LLM_MODEL_NAME: gemini-2.5-flash
LLM_MAX_TOKENS: 1000
LLM_TEMPERATURE: 0.1
VALIDATE_ALL_CODEBASE: true
APPLY_FIXES: all
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE: commit
PLUGINS:
  - https://raw.githubusercontent.com/wesley-dean/mega-linter-plugin-dclint/refs/heads/main/mega-linter-plugin-dclint/dclint.megalinter-descriptor.yml
ENABLE:
  - ACTION
  - DOCKERFILE
  - REPOSITORY
  - YAML
  - MARKDOWN
  - JSON
ENABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - PYTHON_BANDIT
  - DOCKERFILE_DCLINT
DISABLE_LINTERS:
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_MYPY
  - REPOSITORY_DUSTILOCK
DOCKERFILE_DCLINT_ARGUMENTS: "--fix"
EXCLUDED_DIRECTORIES:
  - ".venv"
PRINT_ALL_FILES: true
FILTER_REGEX_EXCLUDE: '(\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|TEMPLATES)'
PYTHON_DEFAULT_STYLE: ruff
PYTHON_RUFF_CONFIG_FILE: .github/lint/.ruff.toml
PYTHON_RUFF_FORMAT_CONFIG_FILE: .github/lint/.ruff.toml
PYTHON_BANDIT_CONFIG_FILE: .github/lint/.bandit.yaml
REPOSITORY_CHECKOV_CONFIG_FILE: .github/lint/.checkov.yaml
DOCKERFILE_HADOLINT_CONFIG_FILE: .github/lint/.hadolint.yaml
REPOSITORY_TRIVY_CONFIG_FILE: .github/lint/.trivy.yaml
YAML_YAMLLINT_CONFIG_FILE: .github/lint/.yamllint.yaml
GITHUB_STATUS_REPORTER: true
SARIF_REPORTER: true
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (\.github|docs/licenses)
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".venv"
# REPOSITORY_TRUFFLEHOG_ARGUMENTS:
#   - --exclude-paths=.trufflehogignore
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: true
EMAIL_REPORTER: true
FILEIO_REPORTER: true
JSON_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
