name: Chattr
services:
  vocalizr:
    image: ghcr.io/alphaspheredotai/vocalizr:latest
    user: root
    ports:
      - "7860:7860"
    volumes:
      - huggingface:/home/nonroot/hf
      - results:/home/nonroot/results
      - logs:/home/nonroot/logs
    post_start:
      - command: chown -R nonroot:nonroot /home/nonroot
        user: root
      - command: chmod -R 755 /home/nonroot
        user: root
    environment:
      - GRADIO_SERVER_PORT=7860
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-o"
        - "/dev/null"
        - "-f"
        - "-s"
        - "-w"
        - "'Status: %{http_code}, Time: %{time_total}s'"
        - "http://localhost:7860/"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
      start_interval: 5s
  vector_database:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
volumes:
  huggingface:
  results:
  logs:
  qdrant_storage:
