[project]
name = "chattr"
version = "0.0.39"
description = "App part of the Chatacter Backend"
readme = "README.md"
authors = [
  { name = "Mohamed Hisham Abdelzaher", email = "mohamed.hisham.abdelzaher@gmail.com" },
]
requires-python = ">=3.14, <3.15"
dependencies = [
  "agno[google,qdrant,os,mcp,openai]>=2.5.13",
  "ddgs>=9.11.2",
  "fastembed>=0.8.1",
  "gradio[mcp]>=5.48.0",
  "pydantic-extra-types>=2.11.1",
  "rich>=14.3.3",
]
scripts = { chattr = "chattr.__main__:main" }

[build-system]
build-backend = "uv_build"
requires = ["uv_build"]

[dependency-groups]
dev = [
  "doppler-env>=0.3.1",
  "pre-commit>=4.5.1",
  "pytest-emoji>=0.2.0",
  "pytest-md>=0.2.0",
  "pytest-mergify>=2025.9.24.2",
  "ruff>=0.13.3",
  "ty>=0.0.1a20",
  "uv-build>=0.11.3",
]
