name: GHCR Container
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: AlphaSphereDotAI
          token: ${{ secrets.GH_TOKEN }}
          image-names: "container-retention-policy"
          image-tags: "*pr*"
          cut-off: 2w 3d
          dry-run: true
