name: GHCR Container
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  clean:
    runs-on: ubuntu-latest
    name: Cleaning GHCR
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GH_TOKEN }}
          image-names: ${{ github.event.repository.name }}
          image-tags: "!latest !*.*.*"
          cut-off: 1s
