name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
permissions: read-all
jobs:
  compatibility:
    name: Check Dependency Compatibility
    runs-on: ubuntu-latest
    environment:
      name: code_quality
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Devenv
        uses: AlphaSphereDotAI/helpr_action/ci/setup/devenv@v0.0.62
      - name: Run dependency compatibility check
        uses: AlphaSphereDotAI/helpr_action/ci/test/dependency_compatibility@v0.0.62
        with:
          tool: uv
  lint:
    name: Lint
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
      actions: read
    needs: compatibility
    uses: ./.github/workflows/.lint.yaml
    secrets: inherit
  image:
    name: Test Image
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      security-events: write
      actions: read
    needs: compatibility
    uses: ./.github/workflows/.docker.yaml
    with:
      is_test: true
      registry: ghcr.io
      install_source: git+${{ github.event.repository.html_url }}@${{ github.sha }}
    secrets: inherit
