name: Cache Trunk
on:
  push:
    branches:
      - main
    paths:
      - .trunk/trunk.yaml
permissions: read-all
jobs:
  cache_trunk:
    name: Cache Trunky
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Trunk Check
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1
        with:
          check-mode: populate_cache_only
